### ISSUE TITLE
How to disable Dynamic reconfig enabled while running in docker 

### ISSUE THREAD

**Issue by LahotiSourabh** [31z4/zookeeper-docker#111]
I am try to disable Dynamic Reconfig while running zookeeper on docker as this is causing issue while running zookeeper and Solr on AWS ECS Fargate environment. 

Running environment: 
Docker  Image: Zookeeper:latest version 
Docker Image: Solr 8.6 version 
Docker compose file: 
zoo1:
    image: zookeeper:latest
    #container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    volumes:
      - ./data/zoo-1/data:/data
      - ./data/zoo-1/conf:/conf
      - ./data/zoo-1/datalog:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "*"

solr3:
    image: solr:8.2
    ports:
     - "8983:8983"
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    volumes:
      - ./data/solr3/data:/var/solr

Please find attached screen shot that contain error - It looks like zookeeper is updating solr with zookeeper cluster server details that is configured as ZOO_SERVERS: server.1=**0.0.0.0**:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

<img width="726" alt="Screen Shot 2020-09-16 at 9 05 43 PM" src="https://user-images.githubusercontent.com/65667173/93538339-8c31f300-f913-11ea-875b-476d881e70c7.png">

**Comment by 31z4** [comment]
I'm not sure if the issue is related to the Docker image itself. Starting from 3.5.3 dynamic reconfiguration feature is disabled by default (see https://zookeeper.apache.org/doc/r3.6.2/zookeeperReconfig.html). This is also true for this Docker image.

If you want to try setting some additional configuration parameters that are not covered by the image environment variables you can use `ZOO_CFG_EXTRA` environment variable for that. See https://hub.docker.com/_/zookeeper/:
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/3657959/93694702-6cbfe380-fb28-11ea-8016-3813b2e29493.png">

Also, it may worth reaching up upstream maintainers: https://issues.apache.org/jira/projects/ZOOKEEPER

**Comment by 31z4** [comment]
Closing it because the issue seems to be inactive for quite some time now.
