### ISSUE TITLE
"Using Docker Swarm when running Zookeeper"?

### ISSUE THREAD

**Issue by bluepuma77** [31z4/zookeeper-docker#16]
I found this sentence in the Readme to be really promising: 

> Consider using Docker Swarm when running Zookeeper in replicated mode.

Is this actual possible to run Zookeeper with Docker Swarm on multiple servers? In "real" swarm mode, where I can easily just scale it up from 3 to 5 servers? How would I do that? Don't I need to set all other Zookeeper server (IP) addresses via environment variable?

So far I found only Elastic to be easily docker-swarm-scalable, thanks to [DZone](https://dzone.com/articles/making-elasticsearch-in-docker-swarm-elastic). Would love to see this possible with Zookeeper, Apache Kafka, Apache NiFi and Hadoop/HDFS.

**Comment by si-harps** [comment]
Is there any update on this? I'm keen to run a zookeeper ensemble across a Docker Swarm. It's unclear how to set the required variables (ZOO_MY_ID, ZOO_SERVERS) when deploying a stack either globally or using replicas. Any feedback would be much appreciated.

**Comment by 31z4** [comment]
The solution to this will be pretty complicated. You would have to use `Consult` as a service registry and `Consul Template` to change Zookeeper configuration when new container is added or an existing container removed. And then you also have to somehow restart all your Zookepers because prior to version 3.5 it doesn't support []

**Comment by 31z4** [comment]
I guess that's what folks from Bandsintow from in their [fork](https://github.com/bandsintown/docker-zookeeper).

**Comment by 31z4** [comment]
Implementing dynamic scaling has become a bit easier with the introduction of the [`3.5.3-beta`](https://github.com/31z4/zookeeper-docker/blob/master/3.5.3-beta/Dockerfile) tag. Because starting from 3.5 Zookeeper now supports [dynamic reconfiguration](https://zookeeper.apache.org/doc/r3.5.3-beta/zookeeperReconfig.html).

**Comment by 31z4** [comment]
Closing it because the issue seems to be inactive for quite some time now.
