### ISSUE TITLE
3.5 not available for ARM CPUs

### ISSUE THREAD

**Issue by agilob** [31z4/zookeeper-docker#87]
3.3 is available for rasbperry pi, but 3.5 is only available for AMD64. Could you please push latest 3.5 for ARM too?

**Comment by 31z4** [comment]
The number of supported architectures comes from the [openjdk](https://hub.docker.com/_/openjdk) base image. Currently in only supports `arm64v8`.

**Comment by cwalker67** [comment]
> The number of supported architectures comes from the [openjdk](https://hub.docker.com/_/openjdk) base image. Currently it only supports `arm64v8`.

Why not use something like `adoptopenjdk` as it supports a plethora of architectures.

**Comment by jonstelly** [comment]
It's worth noting that currently, the zookeeper images aren't even being built or published for arm64 since the `openjdk:8-jessie` image only supports amd64 - https://hub.docker.com/_/zookeeper?tab=tags

I've submitted a pull request for this and added ppc64le and s390x support (because why not).  My PR includes the change to adoptopenjdk and also a bump to jre 11:

https://github.com/31z4/zookeeper-docker/pull/90

**Comment by 31z4** [comment]
Closing it because the issue seems to be inactive for quite some time now.

**Comment by agilob** [comment]
It's inactive because there is a PR open for it.

**Comment by fuzzy76** [comment]
This is really unfortunate, because this is also what prevents this image to work out of the box on never Macs. :(

**Comment by 31z4** [comment]
3.5 is EoL. Consider using at least 3.7 which does support ARM.
